package actions

import (
	"anim8/models"
	"fmt"
	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (SessionGroup)
// DB Table: Plural (session_groups)
// Resource: Plural (SessionGroups)
// Path: Plural (/session_groups)
// View Template Folder: Plural (/templates/session_groups/)

// SessionGroupsResource is the resource for the SessionGroup model
type SessionGroupsResource struct {
	buffalo.Resource
}

// List gets all SessionGroups. This function is mapped to the path
// GET /session_groups
func (v SessionGroupsResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	sessionGroups := &models.SessionGroups{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all SessionGroups from the DB
	if err := q.All(sessionGroups); err != nil {
		return err
	}

	// Add the paginator to the context so it can be used in the template.
	c.Set("pagination", q.Paginator)

	return c.Render(200, r.Auto(c, sessionGroups))
}

// Show gets the data for one SessionGroup. This function is mapped to
// the path GET /session_groups/{session_group_id}
func (v SessionGroupsResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty SessionGroup
	sessionGroup := &models.SessionGroup{}

	// To find the SessionGroup the parameter session_group_id is used.
	if err := tx.Find(sessionGroup, c.Param("session_group_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, sessionGroup))
}

// New renders the form for creating a new SessionGroup.
// This function is mapped to the path GET /session_groups/new
func (v SessionGroupsResource) New(c buffalo.Context) error {
	return c.Render(200, r.Auto(c, &models.SessionGroup{}))
}

// Create adds a SessionGroup to the DB. This function is mapped to the
// path POST /session_groups
func (v SessionGroupsResource) Create(c buffalo.Context) error {
	// Allocate an empty SessionGroup
	sessionGroup := &models.SessionGroup{}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(sessionGroup)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the new.html template that the user can
		// correct the input.
		return c.Render(422, r.JSON(verrs))
	}

	// and redirect to the session_groups index page
	return c.Render(200, r.JSON(sessionGroup))
}

// Edit renders a edit form for a SessionGroup. This function is
// mapped to the path GET /session_groups/{session_group_id}/edit
func (v SessionGroupsResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty SessionGroup
	sessionGroup := &models.SessionGroup{}

	if err := tx.Find(sessionGroup, c.Param("session_group_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, sessionGroup))
}

// Update changes a SessionGroup in the DB. This function is mapped to
// the path PUT /session_groups/{session_group_id}
func (v SessionGroupsResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty SessionGroup
	sessionGroup := &models.SessionGroup{}

	if err := tx.Find(sessionGroup, c.Param("session_group_id")); err != nil {
		return c.Error(404, err)
	}

	// Bind SessionGroup to the html form elements
	if err := c.Bind(sessionGroup); err != nil {
		return err
	}

	verrs, err := tx.ValidateAndUpdate(sessionGroup)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the edit.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, sessionGroup))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", T.Translate(c, "sessionGroup.updated.success"))
	// and redirect to the session_groups index page
	return c.Render(200, r.Auto(c, sessionGroup))
}

// Destroy deletes a SessionGroup from the DB. This function is mapped
// to the path DELETE /session_groups/{session_group_id}
func (v SessionGroupsResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty SessionGroup
	sessionGroup := &models.SessionGroup{}

	// To find the SessionGroup the parameter session_group_id is used.
	if err := tx.Find(sessionGroup, c.Param("session_group_id")); err != nil {
		return c.Error(404, err)
	}

	if err := tx.Destroy(sessionGroup); err != nil {
		return err
	}

	// If there are no errors set a flash message
	c.Flash().Add("success", T.Translate(c, "sessionGroup.destroyed.success"))
	// Redirect to the session_groups index page
	return c.Render(200, r.Auto(c, sessionGroup))
}
